### ISSUE TITLE
Goldest tests fail on recent hspec-golden-aeson versions

### ISSUE THREAD

**Issue by parsonsmatt** [joneshf/rollbar-hs#21]
I'm trying to get `rollbar-hs` working with the latest Stackage resolver, and I'm running into an issue with golden tests failing.

`lts-10.5` (the last LTS resolver before the `nix` change went through) works fine. `lts-11.1` also works. `lts-12.1` fails. `lts-12.1` introduced `aeson-1.3.1.1`, a major bump upgrade from `aeson-1.2.4.0` in `lts-11.22`.

The changelog isn't illuminating:

```
1.3.1.1
Catch 0 denominators when parsing Ratio
1.3.1.0
Fix bug in generically derived FromJSON instances that are using unwrapUnaryRecords, thanks to Xia Li-yao
Allow base-compat 0.10.*, thanks to Oleg Grenrus
1.3.0.0
Breaking changes:

GKeyValue has been renamed to KeyValuePair, thanks to Xia Li-yao
Removed unused FromJSON constraint in withEmbeddedJson, thanks to Tristan Seligmann
Other improvements:

Optimizations of TH toEncoding, thanks to Xia Li-yao
Optimizations of hex decoding when using the default/pure unescape implementation, thanks to Xia Li-yao
Improved error message on Day parse failures, thanks to Gershom Bazerman
Add encodeFile as well as decodeFile* variants, thanks to Markus Hauck
Documentation fixes, thanks to Lennart Spitzner
CPP cleanup, thanks to Ryan Scott
```

The diff is a bit odd.

<details><summary>`diff original faulty.json`</summary>
<p>
```diff
λ ~/Projects/rollbar-hs/ matt/update-stack* diff golden/Item\ \(\)\ \(\':\ Symbol\ \"Authorization\"\ \(\'\[\]\ Symbol\)\).json golden/Item\ \(\)\ \(\':\ Symbol\ \"Authorization\"\ \(\'\[\]\ Symbol\)\).faulty.json 
11c11
<                 "environment": "HB\u0010BuQ\u0017\u00064d*HE\u000b9\u0019\u001b*\u000e\u0013",
---
>                 "environment": "tZ{\u0002^|LLA\u0005;MLB16G\u0017\u0016\u0014",
15c15
<                         "body": ""
---
>                         "body": "n\u001ci\u0012\u001a{Ap\u000e\u001d\n)mxq.\r]UL<xW(JbK$\u0018c"
30c30
<                 "environment": "\u001dGesd@(b)ppm/Z",
---
>                 "environment": "\u000bs_W",
34c34
<                         "body": ")\u0011"
---
>                         "body": "DL%RTxnR( wAB6\u001a\u001c"
38c38
<                 "level": "debug"
---
>                 "level": "error"
40c40
<             "access_token": "\u0018NYo"
---
>             "access_token": "_\u0001{y"
49c49
<                 "environment": "/dt",
---
>                 "environment": "J?\u000f4-w0q\u001d.xssc'VbMIZ~\u001aHer",
57c57
<                 "level": "debug"
---
>                 "level": "critical"
59c59
<             "access_token": "\nwz\u0017"
---
>             "access_token": "G|z?="
68c68
<                 "environment": "\u0003+(up!I",
---
>                 "environment": "SXK7k;>",
72c72
<                         "body": "j+&e\"\u001eqz3pc,\u000elr\u0015+';\u0013\u0017ot\"_\t\u000bm\u0012"
---
>                         "body": "PkS{$2\u001ej7"
78c78
<             "access_token": "fqoNui?+\u000fyAu\u0005>\u0013a"
---
>             "access_token": "r<cbYy\u0010G%\u0018C\u000e;YE#I\"\u001e\u000fD/\u0000k/\u001eN"
87c87
<                 "environment": "V\u001csj\u001edR`T4?\u000eJ\u000cf",
---
>                 "environment": "i^",
91c91
<                         "body": "\u00138=\u0008]\u00030"
---
>                         "body": "F[n"
95c95
<                 "level": "error"
---
>                 "level": "info"
97c97
<             "access_token": ".=#\n$\rD4 /1*c *O"
---
>             "access_token": ""
100c100
< }
---
> }
\ No newline at end of file
```
</p></details>

<details><summary>`diff original faulty.reencoded.json`</summary>
<p>
```diff
λ ~/Projects/rollbar-hs/ matt/update-stack* diff golden/Item\ \(\)\ \(\':\ Symbol\ \"Authorization\"\ \(\'\[\]\ Symbol\)\).json golden/Item\ \(\)\ \(\':\ Symbol\ \"Authorization\"\ \(\'\[\]\ Symbol\)\).faulty.reencoded.json 
100c100
< }
---
> }
\ No newline at end of file
```
</p></details>

Since there's no change in `aeson` that could cause this, I turn my suspicion to QuickCheck and the golden tests themselves. The golden tests are implemented with `hspec-golden-aeson`, which upgraded from `0.5.1.0` in `lts-11.22` to `0.7.0.0` in `lts-12.14`. The [Changelog (not linked from STackage/Hackage)](https://github.com/plow-technologies/hspec-golden-aeson/blob/master/ChangeLog.md) has these possible breaking reasons:

>  # Revision history for hspec-golden-aeson
> 
> ## 0.7.0.0 -- 2018-05-17
> 
> * Breaking change: allow roundtripAndGoldenADTSpecs test to pass when random samples generated from the seed in the golden file do not produce the same Haskell samples, but yet decoding and re-encoding the golden file still produces the same bytes as in the golden file.
> * Add an additional faulty file ending in `.faulty.reencoded.json` when the byte-for-byte decode/encode round-trip fails. This allows you to compare the encoding changes without the noise of the random sample change. In this case, the test will output a message indicating whether decoding the golden file produces the same Haskell values as decoding the re-encoded files. If they produce the same values, that is likely a minor encoding change, but still a change so tests fail.
> * Add `RandomMismatchOption` to `Settings` so you can have the old behavior of failing tests when random samples change.
> 
> ## 0.6.0.0 -- 2018-01-04
> 
> * Test encoding in `roundtripAndGoldenADTSpecs' and 'roundtripAndGoldenADTSpecsWithSettings` functions. This may break current tests because only decoding was tested previously.

So, it looks like "the generation changed with an updated QuickCheck having different seed behavior" is not a culprit, since 0.7.0.0 made that resilient. The other entry ("test encoding") seems like a viable candidate. The explanation of `faulty.reencoded.json` is also helpful.

The error message from the test suite:

```
JSON encoding of (Item () (': Symbol "Authorization" ('[] Symbol)))
  allows to encode values with aeson and read them back
    +++ OK, passed 100 tests.
JSON encoding of (Item () (': Symbol "Authorization" ('[] Symbol)))

WARNING: Encoding new random samples do not match golden/Item () (': Symbol "Authorization" ('[] Symbol)).json.
  Testing round-trip decoding/encoding of golden file.

INFO: Written the reencoded goldenFile into golden/Item () (': Symbol "Authorization" ('[] Symbol)).faulty.reencoded.json.

INFO: Written the current encodings into golden/Item () (': Symbol "Authorization" ('[] Symbol)).faulty.json.
  produces the same JSON as is found in golden/Item () (': Symbol "Authorization" ('[] Symbol)).json FAILED [1]
```

Weird. I'm not sure what to make of this. [This is the source for the test library that is failing](https://github.com/plow-technologies/hspec-golden-aeson/blob/master/src/Test/Aeson/Internal/GoldenSpecs.hs#L86-L106). Since we're getting the `expectationFailure`, that means that `encode newSamples == encode goldenSamples` is false, as well as `encodePretty goldenSamples == goldenBytes`. 

In `writeReencodedComparisonFile`, we write to `.faulty.reencoded.json`, which has the `encodePretty goldenSamples` - `goldenSamples` is the stuff we load out from the old file. So `diff original faulty.reencoded.json` coming up with *only a newline at end of file difference* is good evidence that there is no change in encoding/decoding behavior, and that the *test library* needs to account for this case.

In `writeComparisonFile newSamples`, it writes the *new* samples derived from the same `goldenSeed`. Since these differ substantially from the original file, we actually *do* have a change in the sample generation for the same seed. But `hspec-golden-aeson-0.7.0.0`  specifically should allow this to succeed. So it's the newline-at-end-of-file that's the problem.

**Comment by parsonsmatt** [comment]
Closing as the issue is properly in `hspec-golden-aeson`

**Comment by joneshf** [comment]
Heya! As a heads-up, the actual code for this moved to https://github.com/joneshf/open-source/tree/e3412fc68c654d89a8d3af4e12ac19c70e3055ec/packages/rollbar-hs (similar for the other Rollbar packages I maintain). I haven't taken the time to remove these repos or fix where the documentation points to yet. I haven't really done anything with this stuff in a while, so it might take me a minute to get up to date.

FWIW, I seem to remember those golden tests being really finicky and having to do annoying things to update them all the time. So basically, don't worry too much if things have to change there, so long as it's not like moving from JSON to YAML, changing the casing of fields, or something else equally big.

I'll try to figure this stuff out soon and get your changes in.
